spring:
  application:
    name: ArksCycle
  main:
    web-application-type: none
  config:
    import: configs/cloud-music.yml
task:
  scheduled:
    cron: 0 0 4 * * ?
concat:
  author: ArcSurge
  version: v0.0.1
  created: 2024/08/06
  github: https://github.com/ArcSurge
  repository: https://github.com/ArcSurge/ArksCycle
logging:
  level:
    root: debug